language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    - php: 5.4
      env: PHPCS=1

install:
   - composer install
   - npm install -g bower
   - bower install

script: 
   - sh -c "if [ '$PHPCS' != '1' ]; then cd ./app && ../vendor/cakephp/cakephp/lib/Cake/Console/cake test app AllTests --stderr; fi"
   - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./app; fi;"

before_script:
   - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs --config-set installed_paths ./vendor/cakephp/cakephp-codesniffer; fi"
   - chmod -R 777 ./tmp
   - mysql -e 'create database caffeinated_test;'
   - echo "<?php 
     class DATABASE_CONFIG {
     public \$test = array(
       'datasource' => 'Database/Mysql',
       'database' => 'caffeinated_test',
       'host' => 'localhost',
       'login' => 'travis',
       'password' => '',
       'persistent' => false,
     );
     }" > ./app/Config/database.php
