language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: DB=pgsql

    - php: 5.4
      env: DB=sqlite-mem

    - php: 5.4
      env: DB=sqlite-file

install:
   - composer install
   - npm install -g bower
   - bower install

script: 
   - cd ./app && ../vendor/cakephp/cakephp/lib/Cake/Console/cake test app AllTests --stderr

before_script:
   - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE caffeinated_test;'; fi"
   - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE caffeinated_test;' -U postgres; fi"
   - chmod -R 777 ./tmp
   - mv ./app/Config/database.php.test ./app/Config/database.php
