language: php

php:
  - 5.4
  - 5.5
  - 5.6

notifications:
  email: false

install:
   - composer install
   - npm install -g bower
   - bower install

script: 
   - cd ./app && ../vendor/cakephp/cakephp/lib/Cake/Console/cake test app AllTests --stderr

before_script:
   - pwd
   - chmod -R 777 ./tmp
   - mysql -e 'create database caffeinated_test;'
   - echo "<?php 
     class DATABASE_CONFIG {
     public \$test = array(
       'datasource' => 'Database/Mysql',
       'database' => 'caffeinated_test',
       'host' => 'localhost',
       'login' => 'travis',
       'password' => '',
       'persistent' => false,
     );
     }" > ./app/Config/database.php
